### ISSUE TITLE
Error: TS2345: Argument of type W3CWebSocket is not assignable to parameter of type 'Options'

### ISSUE THREAD

**Issue by igrzhukovich** [vitalets/websocket-as-promised#36]
Thanks for the library it's really helpful. But I got an error on the built typescript project.
The problem is that I use W3CWebSocket in the createWebSocket property but in the Options interface I should return WebSocket type.

```
const wspParams = {
  createWebSocket: (url: string) => new W3CWebSocket(url),
}
```

```
declare interface Options {
    createWebSocket?: (url: string) => WebSocket;
}
```
https://github.com/vitalets/websocket-as-promised/blob/master/types/options.d.ts#L5

TS2345: Argument of type '{ createWebSocket: (url: string) => W3CWebSocket; packMessage: (data: object) => string; unpackMessage: (data: string) => any; attachRequestId: (data: object, requestId: string) => { id: string; }; extractRequestId: (data: {    id: string;}) => string; timeout: number; }' is not assignable to parameter of type 'Options'.

**Comment by vitalets** [comment]
Are you using it in nodejs or browser? I mean from where do you get W3CWebSocket type?

**Comment by igrzhukovich** [comment]
@vitalets nodejs

**Comment by vitalets** [comment]
So, the reason is that `w3cwebsocket` from [websocket](https://github.com/theturtle32/WebSocket-Node) package does not actually match browser [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) :(
Some methods are missing (and types [are missing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d84503d81af4a0e1dd520244ab0b54fafa23acf0/types/websocket/index.d.ts#L748) as well):
```
Type 'w3cwebsocket' is missing the following properties from type 'WebSocket': addEventListener, removeEventListener, dispatchEvent
```

The solution for most cases is to cast to browser WebSocket:
```ts
import WebSocketAsPromised from 'websocket-as-promised';
import { w3cwebsocket as W3CWebSocket } from 'websocket';

const wsp = new WebSocketAsPromised(wsUrl, {
  createWebSocket: url => new W3CWebSocket(url) as unknown as WebSocket,
});
```
